import { Skeleton } from "@/components/ui/skeleton";

/** Shows a content-only POS placeholder while the persistent workspace shell remains visible. */
export default function PosLoading() {
  return <main aria-busy="true" aria-label="Memuat register kasir" className="max-w-none px-3 py-3 pb-40 sm:px-4 sm:py-4 xl:pb-4" id="main-content"><span className="sr-only" role="status">Memuat register kasir…</span><div className="overflow-hidden rounded-2xl border bg-card shadow-sm xl:grid xl:h-[calc(100svh-2rem)] xl:min-h-[42rem] xl:grid-cols-[minmax(0,1fr)_22rem]">
    <section className="flex min-h-0 min-w-0 flex-col xl:h-full">
      <header className="border-b p-3 sm:p-4"><div className="flex items-center gap-3"><Skeleton className="hidden size-12 shrink-0 xl:block" /><div className="hidden min-w-40 space-y-2 sm:block"><Skeleton className="h-4 w-28" /><Skeleton className="h-3 w-20" /></div><Skeleton className="h-12 min-w-0 flex-1 rounded-lg sm:mx-auto sm:max-w-xl" /><div className="hidden gap-2 2xl:flex"><Skeleton className="h-7 w-24 rounded-full" /><Skeleton className="h-7 w-28 rounded-full" /></div></div><div className="mt-3 flex gap-2 overflow-hidden"><Skeleton className="h-7 w-20 shrink-0 rounded-lg" />{Array.from({ length: 3 }, (_, index) => <Skeleton className="h-7 w-24 shrink-0 rounded-lg" key={index} />)}</div></header>
      <div className="flex min-h-0 flex-1 xl:overflow-hidden"><aside className="hidden w-28 shrink-0 border-r p-2 xl:block">{Array.from({ length: 6 }, (_, index) => <Skeleton className="mb-2 h-20 rounded-xl" key={index} />)}</aside><div className="min-h-0 min-w-0 flex-1 bg-muted/20 p-3 sm:p-4 xl:overflow-hidden"><div className="flex gap-2 overflow-hidden pb-2 xl:hidden">{Array.from({ length: 4 }, (_, index) => <Skeleton className="h-7 w-20 shrink-0 rounded-lg" key={index} />)}</div><div className="mb-3 flex items-end justify-between gap-4"><div className="space-y-2"><Skeleton className="h-5 w-32" /><Skeleton className="h-3 w-48" /></div><Skeleton className="h-3 w-16" /></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4 2xl:grid-cols-5">{Array.from({ length: 10 }, (_, index) => <div className="overflow-hidden rounded-xl border bg-card" key={index}><Skeleton className="aspect-square rounded-none" /><div className="space-y-3 p-3"><Skeleton className="h-4 w-3/4" /><div className="flex justify-between gap-3"><Skeleton className="h-3 w-16" /><Skeleton className="h-3 w-14" /></div></div><Skeleton className="h-1 rounded-none" /></div>)}</div></div></div>
    </section>
    <aside className="hidden min-h-0 flex-col border-l xl:flex"><div className="border-b p-3"><Skeleton className="h-16 rounded-xl" /></div><div className="border-b p-4"><div className="flex justify-between gap-3"><Skeleton className="h-6 w-36" /><Skeleton className="h-6 w-14 rounded-full" /></div><Skeleton className="mt-2 h-4 w-48" /></div><div className="flex-1 p-4"><Skeleton className="h-full min-h-56 rounded-xl" /></div><div className="space-y-3 border-t bg-muted/25 p-4">{Array.from({ length: 4 }, (_, index) => <div className="flex justify-between" key={index}><Skeleton className="h-4 w-20" /><Skeleton className="h-4 w-24" /></div>)}<Skeleton className="mt-4 h-12 w-full rounded-lg" /></div></aside>
  </div><Skeleton className="fixed right-4 bottom-[calc(5.4rem+env(safe-area-inset-bottom))] left-4 z-30 h-14 rounded-xl xl:hidden" /></main>;
}
